# Generated by Django 4.2.4 on 2023-12-18 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Strain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=45)),
                ('kingdom', models.CharField(max_length=45)),
                ('phylum', models.CharField(max_length=45)),
                ('tax_class', models.CharField(max_length=45)),
                ('tax_order', models.CharField(max_length=45)),
                ('family', models.CharField(max_length=45)),
                ('genus', models.CharField(max_length=45)),
                ('sci_name', models.CharField(max_length=45)),
                ('strain_desc', models.CharField(max_length=200)),
                ('species', models.CharField(max_length=45)),
                ('is_type_strain', models.BooleanField()),
                ('is_bacdive', models.BooleanField()),
                ('strain_desig', models.CharField(max_length=45)),
                ('strain_hist', models.CharField(max_length=45)),
                ('NCBI_tax_id_strain', models.CharField(max_length=45)),
                ('NCBI_tax_id_species', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Cul_coll_no',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cn', models.CharField(max_length=45)),
                ('cnn', models.CharField(max_length=45)),
                ('strain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cc_nums', to='api.strain')),
            ],
        ),
    ]
