# Generated by Django 4.2.4 on 2023-12-18 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cul_coll_no',
            name='cnn',
        ),
        migrations.RemoveField(
            model_name='strain',
            name='NCBI_tax_id_species',
        ),
        migrations.RemoveField(
            model_name='strain',
            name='NCBI_tax_id_strain',
        ),
        migrations.RemoveField(
            model_name='strain',
            name='kingdom',
        ),
        migrations.RemoveField(
            model_name='strain',
            name='strain_desig',
        ),
    ]
