# Generated by Django 4.2.4 on 2023-12-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_cul_coll_no_cnn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cul_coll_no',
            name='cn',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='strain',
            name='domain',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='strain',
            name='family',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='strain',
            name='genus',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='strain',
            name='phylum',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='strain',
            name='sci_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='strain',
            name='species',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='strain',
            name='strain_hist',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='strain',
            name='tax_class',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='strain',
            name='tax_order',
            field=models.CharField(max_length=100),
        ),
    ]
