# Generated by Django 4.2.4 on 2023-12-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_cul_coll_no_cn_alter_strain_domain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strain',
            name='strain_hist',
            field=models.CharField(max_length=1000),
        ),
    ]
