# Generated by Django 4.2.4 on 2023-12-19 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_strain_strain_hist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strain',
            name='strain_hist',
        ),
        migrations.AlterField(
            model_name='strain',
            name='strain_desc',
            field=models.CharField(max_length=250),
        ),
        migrations.CreateModel(
            name='Strain_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str_hist', models.CharField(max_length=100)),
                ('strain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='str_hst', to='api.strain')),
            ],
        ),
    ]
